name: mmtf-pyspark 

channels:
  - conda-forge
  - anaconda
  - bioconda 

dependencies:
  - python=3.7
  - openjdk=8.0.152
  - pyspark=2.4.0
  - biopython=1.72
  - numba=0.41.0
  - numpy=1.16.1
  - jupyterlab=3.2.5
  - py3Dmol=0.8.0
  - ipywidgets=7.6.5
  - pip
  - pip:
      - git+https://github.com/sbl-sdsc/mmtf-pyspark.git 

variables:
  SPARK_DRIVER_MEMORY: 16G
  SPARK_DRIVER_MAXRESULTSIZE: 4G
  SPARK_WORKER_MEMORY: 4G
